
nohup: ignoring input
Watching for file changes with StatReloader
[22/Feb/2023 16:54:10] "GET /lifelog/v2/ HTTP/1.1" 200 11743
[22/Feb/2023 16:54:10] "GET /static/jquery-3.5.1/jquery.min.js HTTP/1.1" 200 89476
[22/Feb/2023 16:54:10] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 194901
[22/Feb/2023 16:54:10] "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 200 60404
[22/Feb/2023 16:54:10] "GET /static/bootstrap/js/bootstrap.min.js.map HTTP/1.1" 200 216913
[22/Feb/2023 16:54:10] "GET /static/bootstrap/css/bootstrap.min.css.map HTTP/1.1" 200 522639
[22/Feb/2023 16:54:17] "GET /lifelog/v2/ HTTP/1.1" 200 11743
[22/Feb/2023 16:54:17] "GET /static/jquery-3.5.1/jquery.min.js HTTP/1.1" 200 89476
[22/Feb/2023 16:54:17] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 194901
[22/Feb/2023 16:54:17] "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 200 60404
[22/Feb/2023 16:54:17] "GET /static/bootstrap/js/bootstrap.min.js.map HTTP/1.1" 200 216913
[22/Feb/2023 16:54:17] "GET /static/bootstrap/css/bootstrap.min.css.map HTTP/1.1" 200 522639
[22/Feb/2023 16:54:27] "GET /lifelog/ HTTP/1.1" 200 13576
[22/Feb/2023 16:54:28] "GET /lifelog/log/ HTTP/1.1" 200 5538
[22/Feb/2023 16:54:55] "GET /static/bootstrap/js/bootstrap.min.js.map HTTP/1.1" 200 216913
[22/Feb/2023 16:54:55] "GET /static/bootstrap/css/bootstrap.min.css.map HTTP/1.1" 200 522639
/www/django_www/app01/utils/form.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
February 22, 2023 - 16:54:10
Django version 3.2, using settings 'django_www.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[22/Feb/2023 16:55:32] "GET /lifelog/v2/ HTTP/1.1" 200 11739
/www/django_www/app01/utils/form.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
February 22, 2023 - 16:55:30
Django version 3.2, using settings 'django_www.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[22/Feb/2023 16:56:42] "GET /lifelog/log/ HTTP/1.1" 200 5538
/www/django_www/app01/utils/form.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
February 22, 2023 - 16:56:40
Django version 3.2, using settings 'django_www.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/django_www/django_www/urls.py", line 3, in <module>
    from app01.views import index, learn_bootstrap, learn_js, learn_react, lifelog, music, admin
  File "/www/django_www/app01/views/lifelog.py", line 4, in <module>
    from app01.utils.form import LogModeForm, LifeLogEdit
  File "/www/django_www/app01/utils/form.py", line 14, in <module>
    class LogModeForm(BootstrapModelForm):
  File "/www/django_www/app01/utils/form.py", line 17, in LogModeForm
    class Meta:
  File "/www/django_www/app01/utils/form.py", line 24, in Meta
    "weather": forms.CharField(attrs={"autocomplete": "off"}),
  File "/usr/local/lib/python3.8/dist-packages/django/forms/fields.py", line 216, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'attrs'
nohup: ignoring input
Watching for file changes with StatReloader
/www/django_www/app01/utils/form.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
February 22, 2023 - 16:57:51
Django version 3.2, using settings 'django_www.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[22/Feb/2023 17:00:20] "GET /lifelog/log/ HTTP/1.1" 200 5557
[22/Feb/2023 17:00:25] "GET /lifelog/v2/ HTTP/1.1" 200 11758
/www/django_www/app01/views/login.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
February 22, 2023 - 17:00:20
Django version 3.2, using settings 'django_www.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[22/Feb/2023 17:09:14] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 100
[22/Feb/2023 17:09:17] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:09:21] "GET /lifelog/v2/ HTTP/1.1" 200 11808
[22/Feb/2023 17:09:23] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 100
[22/Feb/2023 17:09:25] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:09:39] "GET /lifelog/ HTTP/1.1" 200 13489
[22/Feb/2023 17:09:40] "GET /lifelog/del/7034001924139651072/ HTTP/1.1" 302 0
[22/Feb/2023 17:09:40] "GET /lifelog/ HTTP/1.1" 200 13489
[22/Feb/2023 17:09:40] "GET /lifelog/del/7034001893219241984/ HTTP/1.1" 302 0
[22/Feb/2023 17:09:41] "GET /lifelog/ HTTP/1.1" 200 13576
[22/Feb/2023 17:09:49] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:13:34] "GET /lifelog/v2/ HTTP/1.1" 200 11986
[22/Feb/2023 17:13:39] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:17:34] "GET /lifelog/v2/ HTTP/1.1" 200 11986
[22/Feb/2023 17:17:38] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:17:58] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:20:36] "GET /lifelog/v2/ HTTP/1.1" 200 11987
[22/Feb/2023 17:20:39] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:21:24] "GET /lifelog/v2/ HTTP/1.1" 200 12043
[22/Feb/2023 17:21:27] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:22:18] "GET /lifelog/ HTTP/1.1" 200 13475
[22/Feb/2023 17:22:20] "GET /lifelog/del/7034004951684747264/ HTTP/1.1" 302 0
[22/Feb/2023 17:22:20] "GET /lifelog/ HTTP/1.1" 200 13481
[22/Feb/2023 17:22:20] "GET /lifelog/del/7034004749670289408/ HTTP/1.1" 302 0
[22/Feb/2023 17:22:20] "GET /lifelog/ HTTP/1.1" 200 13477
[22/Feb/2023 17:22:21] "GET /lifelog/del/7034003991235268608/ HTTP/1.1" 302 0
[22/Feb/2023 17:22:21] "GET /lifelog/ HTTP/1.1" 200 13490
[22/Feb/2023 17:22:22] "GET /lifelog/del/7034004077474353152/ HTTP/1.1" 302 0
[22/Feb/2023 17:22:22] "GET /lifelog/ HTTP/1.1" 200 13498
[22/Feb/2023 17:22:23] "GET /lifelog/del/7034002989195071488/ HTTP/1.1" 302 0
[22/Feb/2023 17:22:23] "GET /lifelog/ HTTP/1.1" 200 13498
[22/Feb/2023 17:25:51] "GET /lifelog/v2/ HTTP/1.1" 200 12053
[22/Feb/2023 17:29:27] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:29:33] "GET /static/bootstrap/css/bootstrap.min.css.map HTTP/1.1" 200 522639
[22/Feb/2023 17:29:33] "GET /static/bootstrap/js/bootstrap.min.js.map HTTP/1.1" 200 216913
[22/Feb/2023 17:29:37] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:29:56] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:30:51] "GET /lifelog/v2/ HTTP/1.1" 200 12136
[22/Feb/2023 17:30:51] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 194901
[22/Feb/2023 17:30:51] "GET /static/jquery-3.5.1/jquery.min.js HTTP/1.1" 200 89476
[22/Feb/2023 17:30:51] "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 200 60404
[22/Feb/2023 17:30:51] "GET /static/bootstrap/css/bootstrap.min.css.map HTTP/1.1" 200 522639
[22/Feb/2023 17:30:51] "GET /static/bootstrap/js/bootstrap.min.js.map HTTP/1.1" 200 216913
[22/Feb/2023 17:33:03] "GET /admin/ HTTP/1.1" 200 9560
/www/django_www/app01/views/lifelog_v2.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
February 22, 2023 - 17:04:45
Django version 3.2, using settings 'django_www.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/www/django_www/app01/views/lifelog_v2.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
February 22, 2023 - 17:41:31
Django version 3.2, using settings 'django_www.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/www/django_www/app01/views/lifelog_v2.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
February 22, 2023 - 17:41:46
Django version 3.2, using settings 'django_www.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/django_www/django_www/urls.py", line 4, in <module>
    from app01.views import login, task, lifelog_v2
  File "/www/django_www/app01/views/lifelog_v2.py", line 33
    'form_title':title，
                      ^
SyntaxError: invalid character in identifier
/www/django_www/app01/views/lifelog_v2.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
[22/Feb/2023 17:45:54] "GET /lifelog/ HTTP/1.1" 200 13476
Internal Server Error: /lifelog/v2/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/www/django_www/app01/views/lifelog_v2.py", line 31, in lifelog_v2
    return render(request, 'lifelog_v2.html',
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 212, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'css' appears more than once
[22/Feb/2023 17:45:58] "GET /lifelog/v2/ HTTP/1.1" 500 151973
/www/django_www/app01/views/lifelog.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
February 22, 2023 - 17:45:46
Django version 3.2, using settings 'django_www.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[22/Feb/2023 17:46:39] "GET /lifelog/ HTTP/1.1" 200 13476
Internal Server Error: /lifelog/v2/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/www/django_www/app01/views/lifelog_v2.py", line 31, in lifelog_v2
    return render(request, 'lifelog_v2.html',
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 212, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'bodyContent' appears more than once
[22/Feb/2023 17:47:17] "GET /lifelog/v2/ HTTP/1.1" 500 152692
Internal Server Error: /lifelog/v2/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/www/django_www/app01/views/lifelog_v2.py", line 31, in lifelog_v2
    return render(request, 'lifelog_v2.html',
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 212, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'bodyContent' appears more than once
[22/Feb/2023 17:48:02] "GET /lifelog/v2/ HTTP/1.1" 500 151520
[22/Feb/2023 17:48:11] "GET /lifelog/v2/ HTTP/1.1" 200 20543
[22/Feb/2023 17:48:15] "GET /lifelog/v2/?page=2 HTTP/1.1" 200 20802
[22/Feb/2023 17:48:16] "GET /lifelog/v2/?page=1 HTTP/1.1" 200 20543
[22/Feb/2023 17:48:19] "GET /lifelog/del/7034006965613367296/ HTTP/1.1" 302 0
[22/Feb/2023 17:48:19] "GET /lifelog/ HTTP/1.1" 200 13501
/www/django_www/app01/views/lifelog_v2.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
February 22, 2023 - 17:46:38
Django version 3.2, using settings 'django_www.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/www/django_www/django_www/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
February 22, 2023 - 17:49:24
Django version 3.2, using settings 'django_www.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[22/Feb/2023 17:50:46] "GET /lifelog/v2/ HTTP/1.1" 200 20586
[22/Feb/2023 17:51:13] "GET /lifelog/v2/ HTTP/1.1" 200 20586
[22/Feb/2023 17:51:14] "GET /lifelog/v2/ HTTP/1.1" 200 20586
[22/Feb/2023 17:51:33] "GET /lifelog/v2/ HTTP/1.1" 200 20619
[22/Feb/2023 17:51:52] "GET /lifelog/v2/ HTTP/1.1" 200 20616
[22/Feb/2023 17:52:25] "GET /lifelog/v2/ HTTP/1.1" 200 20445
[22/Feb/2023 17:52:31] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:52:32] "GET /lifelog/v2/ HTTP/1.1" 200 20420
[22/Feb/2023 17:52:34] "GET /lifelog/v2/ HTTP/1.1" 200 20420
[22/Feb/2023 17:52:35] "GET /lifelog/v2/ HTTP/1.1" 200 20420
[22/Feb/2023 17:52:35] "GET /lifelog/v2/ HTTP/1.1" 200 20420
[22/Feb/2023 17:52:35] "GET /lifelog/v2/ HTTP/1.1" 200 20420
[22/Feb/2023 17:52:36] "GET /lifelog/v2/ HTTP/1.1" 200 20420
Internal Server Error: /lifelog/v2/del/7034012769859014656/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: lifelog_v2_del() got an unexpected keyword argument 'id'
[22/Feb/2023 17:52:38] "GET /lifelog/v2/del/7034012769859014656/ HTTP/1.1" 500 52829
/www/django_www/django_www/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
February 22, 2023 - 17:50:11
Django version 3.2, using settings 'django_www.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[22/Feb/2023 17:52:58] "GET /lifelog/v2/ HTTP/1.1" 200 20420
[22/Feb/2023 17:53:00] "GET /lifelog/v2/del/7034012769859014656/ HTTP/1.1" 302 0
[22/Feb/2023 17:53:00] "GET /lifelog/v2/ HTTP/1.1" 200 20445
[22/Feb/2023 17:53:01] "GET /lifelog/v2/del/7034007008617566208/ HTTP/1.1" 302 0
[22/Feb/2023 17:53:01] "GET /lifelog/v2/ HTTP/1.1" 200 20462
[22/Feb/2023 17:53:03] "GET /lifelog/v2/del/7034007089399861248/ HTTP/1.1" 302 0
[22/Feb/2023 17:53:03] "GET /lifelog/v2/ HTTP/1.1" 200 20457
[22/Feb/2023 17:53:06] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:53:07] "GET /lifelog/v2/ HTTP/1.1" 200 20457
[22/Feb/2023 17:53:10] "GET /lifelog/v2/del/7034012917175554048/ HTTP/1.1" 302 0
[22/Feb/2023 17:53:10] "GET /lifelog/v2/ HTTP/1.1" 200 20457
[22/Feb/2023 17:53:13] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:53:14] "GET /lifelog/v2/ HTTP/1.1" 200 20457
[22/Feb/2023 17:53:37] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:53:38] "GET /lifelog/v2/ HTTP/1.1" 200 20444
[22/Feb/2023 17:53:39] "GET /lifelog/v2/ HTTP/1.1" 200 20444
[22/Feb/2023 17:53:41] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:53:41] "GET /lifelog/v2/ HTTP/1.1" 200 20419
[22/Feb/2023 17:53:45] "POST /lifelog/v2/add/ajax/ HTTP/1.1" 200 16
[22/Feb/2023 17:53:45] "GET /lifelog/v2/ HTTP/1.1" 200 20426
[22/Feb/2023 17:53:46] "GET /lifelog/v2/del/7034013080820518912/ HTTP/1.1" 302 0
[22/Feb/2023 17:53:46] "GET /lifelog/v2/ HTTP/1.1" 200 20419
[22/Feb/2023 17:53:47] "GET /lifelog/v2/del/7034013065200930816/ HTTP/1.1" 302 0
[22/Feb/2023 17:53:47] "GET /lifelog/v2/ HTTP/1.1" 200 20444
[22/Feb/2023 17:53:48] "GET /lifelog/v2/del/7034013048637624320/ HTTP/1.1" 302 0
[22/Feb/2023 17:53:48] "GET /lifelog/v2/ HTTP/1.1" 200 20460
[22/Feb/2023 17:53:49] "GET /lifelog/v2/del/7034012946766368768/ HTTP/1.1" 302 0
[22/Feb/2023 17:53:50] "GET /lifelog/v2/ HTTP/1.1" 200 20460
